apiVersion: v1
version: 0.4.0
appVersion: "v2.2.0-beta.1"
name: capacity
description: Capacity ensures that the right hardware is available for the required resource load of your Kubernetes cluster at any given time. This helps prevent over-provisioning of your container environment and overspending on your hardware budget.
home: https://github.com/supergiant
icon: https://user-images.githubusercontent.com/26225544/48772264-8abe2200-eccc-11e8-8b7c-e35225aa9030.png
