# Default values for capacity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: supergiant/capacity
  tag: v2.2.0-beta.1
  pullPolicy: IfNotPresent

config:
  args: {}
    # - --log-level=debug
    # - --log-format=json
    # - --log-hooks=syslog
  kubescaler:
    raw: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 450Mi
